# Generated by Django 4.2.1 on 2023-05-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
