# Generated by Django 4.2.1 on 2023-05-21 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0005_shoppingitem_reporter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingitem',
            old_name='reporter',
            new_name='user',
        ),
    ]
